all: insert heap quick counting radix

insert:
	g++ -std=c++11 insert_sort.cpp -o insert

heap:
	g++ -std=c++11 heap_sort.cpp -o heap

quick:
	g++ -std=c++11 quick_sort.cpp -o quick

counting:
	g++ -std=c++11 counting_sort.cpp -o counting

radix:
	g++ -std=c++11 radix_sort.cpp -o radix

clean:
	rm insert heap quick counting radix